@"
name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.py
            requirements.txt
            assets/public_key.pem
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          - name: Build Executable
  run: |
    pip install pyinstaller
    pyinstaller --onefile --name PomodoroTimer main.py
    cp -r assets dist/
    cd dist
    zip release.zip PomodoroTimer.exe assets/*
  
- name: Upload Release Asset
  uses: softprops/action-gh-release@v1
  with:
    files: dist/release.zip
"@ | Out-File -FilePath .github\workflows\release.yml -Encoding utf8
